# Generated by Django 5.1 on 2024-08-24 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserId',
            new_name='Username',
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(code='invalid_password', message='Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')]),
        ),
    ]
