# Generated by Django 5.1 on 2024-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_userid_user_username_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Firstname',
            field=models.CharField(default='Raju', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='Lastname',
            field=models.CharField(default='Rastogi', max_length=10),
        ),
    ]
