# Generated by Django 5.1 on 2024-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('IN', 'INSTAGRAM'), ('TW', 'TWITTER'), ('RE', 'REDDIT'), ('LI', 'LINKEDIN')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.CharField(default='example@email.com', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.ImageField(default='NULL', upload_to='profilePic/'),
        ),
    ]
