# Generated by Django 5.1 on 2024-08-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_account_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.CharField(default='NULL', max_length=70),
        ),
    ]
