# Generated by Django 5.1 on 2024-08-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.TextField(default='NULL'),
        ),
    ]
