# Generated by Django 5.1 on 2024-08-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_date_joined_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Abcd@1234', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
