# Generated by Django 5.1 on 2024-08-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_password_user_password'),
        ('api', '0009_user_password'),
    ]

    operations = [
    ]
